---
- name: Postfix postmap relay pass
  ansible.builtin.command: postmap /etc/postfix/postfix_relay_pass
  changed_when: false

- name: Postfix postmap transport
  ansible.builtin.command: postmap hash:/etc/postfix/transport
  changed_when: false

- name: Postfix postmap sender canonical
  ansible.builtin.command: postmap hash:/etc/postfix/sender_canonical
  changed_when: false

- name: New aliases
  ansible.builtin.command: newaliases
  changed_when: false

- name: Restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted
  when: postfix_service_enabled
