---
- name: Postfix postmap relay pass
  command: postmap /etc/postfix/postfix_relay_pass
  changed_when: false

- name: Postfix postmap transport
  command: postmap hash:/etc/postfix/transport
  changed_when: false

- name: Postfix postmap sender canonical
  command: postmap hash:/etc/postfix/sender_canonical
  changed_when: false

- name: New aliases
  command: newaliases
  changed_when: false

- name: Restart postfix
  service:
    name: postfix
    state: restarted
  when: postfix_service_enabled
