---
- name: Update grub RedHat
  ansible.builtin.command: grub2-mkconfig -o /boot/grub2/grub.cfg
  when: ansible_os_family == 'RedHat'
  listen: Update grub
  changed_when: false

- name: Update grub Debian
  ansible.builtin.command: /usr/sbin/update-grub
  when: ansible_os_family == 'Debian'
  listen: Update grub
  changed_when: false
