---
- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
    enabled: true

- name: Restart systemd-journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted
