---
- name: Import merge.yml
  ansible.builtin.import_tasks: merge.yml
  when: inventory_dir != "None"

- name: Add user ssh authorized keys
  ansible.posix.authorized_key:
    user: "{{ item.user }}"
    key: "{{ item.key }}"
    state: "{{ item.state | default('present') }}"
    comment: "{{ item.comment | default(omit) }}"
  with_items: "{{ _merged_ssh_authorized_keys }}"
  when: _merged_ssh_authorized_keys is defined
