---
- name: Install required deb packages
  ansible.builtin.package:
    name:
      - curl
      - gnupg
      - jq
      - netcat-traditional

- name: Install repository key
  ansible.builtin.shell:
    cmd: set -o pipefail && curl https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor > /usr/share/keyrings/trivy.gpg
    executable: /bin/bash
  args:
    creates: /usr/share/keyrings/trivy.gpg

- name: Add trivy repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/trivy.list
    content: |
      deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb {{ ansible_distribution_release }} main
  register: _add_repo

- name: Install trivy
  ansible.builtin.apt:
    name: trivy
    update_cache: "{{ _add_repo.changed }}"
