---
- name: Install required deb packages
  package:
    name:
      - curl
      - gnupg
      - jq
      - netcat-traditional

- name: Make sure /etc/apt/keyrings/ is there
  ansible.builtin.file:
    path: /etc/apt/keyrings/
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Delete repository key
  file:
    path: /etc/apt/keyrings/trivy.gpg
    state: absent
  when: reinstall_repository_key is defined and reinstall_repository_key

- name: Download repository key (-e reinstall_repository_key=true)
  shell: curl {{ trivy_deb_reposity_key_url }} | gpg --dearmor > /etc/apt/keyrings/trivy.gpg
  args:
    creates: /etc/apt/keyrings/trivy.gpg
  register: __gpgkey

- name: Add trivy repository
  copy:
    dest: /etc/apt/sources.list.d/trivy.list
    content: "{{ trivy_deb_sources_list }}"
  register: __add_repo

- name: Install trivy
  ansible.builtin.apt:
    name: trivy
    update_cache: "{% if __add_repo.changed or __gpgkey.changed %}true{% else %}false{% endif %}"
