---
- name: Include OS tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
- name: Copy trivy-scan.sh
  ansible.builtin.copy:
    src: trivy-scan.sh
    dest: /usr/local/bin/trivy-scan.sh
    mode: "0755"
