---
- name: Install required rpm packages
  package:
    name:
      - jq
      - nmap-ncat

- name: Add trivy repository
  copy:
    dest: /etc/yum.repos.d/trivy.repo
    content: |
      [trivy]
      name=Trivy repository
      baseurl=https://aquasecurity.github.io/trivy-repo/rpm/releases/{{ ansible_distribution_major_version }}/\$basearch/
      gpgcheck=1
      enabled=1
      gpgkey=https://aquasecurity.github.io/trivy-repo/rpm/public.key
    mode: 0644

- name: Install trivy
  ansible.builtin.dnf:
    name: trivy
