---
- name: Install required rpm packages
  package:
    name:
      - jq
      - nmap-ncat

- name: Add trivy repository
  copy:
    dest: /etc/yum.repos.d/trivy.repo
    content: "{{ trivy_rpm_repo }}"
    mode: 0644

- name: Install trivy
  ansible.builtin.dnf:
    name: trivy
