---
apparmor_packages:
  - apparmor

apparmor_parser: /usr/sbin/apparmor_parser

apparmor_service_enabled: true
apparmor_service_name: apparmor
apparmor_service_state: started

# apparmor_profiles:
#   - dest: /etc/apparmor.d/apptainer
#     state: present
#     content: |
#       # Permit unprivileged user namespace creation for apptainer starter
#       abi <abi/4.0>,
#       include <tunables/global>
#       profile apptainer /usr/local/libexec/apptainer/bin/starter{,-suid} flags=(unconfined) {
#         userns,
#         # Site-specific additions and overrides. See local/README for details.
#         include if exists <local/apptainer>
#       }
#
#   - dest: /etc/apparmor.d/local/usr.sbin.cupsd
#     state: absent
#     content: |
#       # Local customizations for CUPS daemon
#       /var/log/cups/custom.log w,
#       /etc/cups/custom.conf r,
#       /opt/printer-driver/** rx,
