---
- name: Include OS vars
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
  tags: always

- name: Install lm sensors
  ansible.builtin.package:
    name: "{{ lmsensors_package }}"
  register: _install_sensors

- name: Setup lm sensors
  ansible.builtin.command: sensors-detect --auto
  changed_when: false
  when: _install_sensors.changed
