---
- name: Include OS vars
  include_vars: "{{ ansible_os_family }}.yml"
  tags: always

- name: Install lm sensors
  package:
    name: "{{ lmsensors_package }}"
  register: _install_sensors

- name: setup lm sensors
  command: "sensors-detect --auto"
  changed_when: false
  when: _install_sensors.changed
