---
- name: "Install package: {{ cronjob_package }}"
  package:
    name: "{{ cronjob_package }}"
  
- name: Apply cronjobs
  cron:
    cron_file: "{{ item.file | default(omit) }}"
    day: "{{ item.day | default('*') }}"
    env: "{{ item.env | default('no') }}"
    hour: "{{ item.hour | default('*') }}"
    job: "{{ item.job }}"
    minute: "{{ item.minute | default('*') }}"
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    user: "{{ item.user | default(omit) }}"
    weekday: "{{ item.weekday | default('*') }}"
  with_items: "{{ cronjob_entries }}"
  when: cronjob_entries is defined
