---
- name: Set /etc/firewalld/zones/public.xml
  ansible.builtin.template:
    src: firewalld_zone.xml.j2
    dest: /etc/firewalld/zones/public.xml
  notify: Restart firewalld

- name: Set LogDenied
  ansible.builtin.lineinfile:
    path: /etc/firewalld/firewalld.conf
    regexp: ^LogDenied
    line: LogDenied={{ firewalld_log_denied }}
  notify: Restart firewalld

- name: Set AllowZoneDrifting
  ansible.builtin.lineinfile:
    path: /etc/firewalld/firewalld.conf
    regexp: ^AllowZoneDrifting
    line: AllowZoneDrifting={{ firewalld_allow_zone_drifting }}
  notify: Restart firewalld

- name: Delete all predefinded zones except public
  ansible.builtin.file:
    path: /etc/firewalld/zones/{{ item }}.xml
    state: absent
  with_items:
    - block
    - dmz
    - drop
    - external
    - home
    - internal
    - trusted
    - work
  notify: Restart firewalld

- name: Set firewalld service
  ansible.builtin.service:
    name: firewalld
    state: "{{ firewalld_service_state }}"
    enabled: "{{ firewalld_service_enabled }}"
