---
- name: Install firewalld
  ansible.builtin.package:
    name: firewalld

- name: Import merge.yml
  ansible.builtin.import_tasks: merge.yml
  when: inventory_dir != "None"

- name: Import firewalld.yml
  ansible.builtin.import_tasks: firewalld.yml
  when: _merged_firewalld_rules is defined
