---
- name: Install firewalld
  package:
    name: firewalld

- name: Import merge.yml
  import_tasks: merge.yml
  when: inventory_dir != "None"

- name: Import firewalld.yml
  import_tasks: firewalld.yml
  when: merged_firewalld_rules is defined
