---
- name: Stop firewalld
  ansible.builtin.service:
    name: firewalld
    state: stopped

- name: Start firewalld
  ansible.builtin.service:
    name: firewalld
    state: started

- name: Restart firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted
