---
- name: Stop firewalld
  service:
    name: firewalld
    state: stopped

- name: Start firewalld
  service:
    name: firewalld
    state: started

- name: Restart firewalld
  service:
    name: firewalld
    state: restarted
