---
- name: Set journald ini file
  community.general.ini_file:
    dest: /etc/systemd/journald.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items: "{{ remote_syslog_journald_ini }}"
  notify: Restart systemd-journald

- name: Install rsyslog
  ansible.builtin.package:
    name: rsyslog

- name: Create rsyslog work dir
  ansible.builtin.file:
    path: /var/spool/rsyslog
    state: directory
    mode: "0700"

- name: Set rsyslog.conf
  ansible.builtin.copy:
    content: "{{ remote_syslog_rsyslog_conf }}"
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart rsyslog
  when: remote_syslog_server is defined and remote_syslog_server != ""

- name: Set rsyslog service
  ansible.builtin.service:
    name: rsyslog
    enabled: "{{ remote_syslog_rsyslog_service_enabled }}"
    state: "{{ remote_syslog_rsyslog_service_state }}"
