---

postfix_service_enabled: true
postfix_service_state: started

# postfix_email_aliases, a 'BlockInFile' inserted 'As is' in /etc/aliases
# postfix_email_aliases: |
#   root: me@example.com

# postfix_main_conf, 'regex', 'line' and 'state' to configure /etc/postfix/main.cf
# postfix_main_conf:
#   - { re: "^mynetworks.*", line: "mynetworks = 127.0.0.0/8 192.168.0.0/16 172.16.0.0/12" }
#   - { re: "^inet_protocols.*", line: "inet_protocols = all" }
#   - { re: "^inet_interfaces.*", line: "inet_interfaces = all" }
#   - { re: "^mydomain.*", line: "mydomain = {{ ansible_domain }}" }
#   - { re: "^myhostname.*", line: "myhostname = {{ ansible_hostname }}" }
#   - { re: "^myorigin.*", line: "myorigin = $myhostname.$mydomain" }
#   - { re: "^mydestination.*", line: "mydestination = localhost, $myhostname, $myhostname.$mydomain" }
#   - { re: "^maillog_file.*", line: "maillog_file = /var/log/maillog", state: "absent" }
#   - { re: "^smtpd_tls_security_level.*", line: "smtpd_tls_security_level = none" }
#   - { re: "^relayhost.*", line: "relayhost = relay.example.com" }
#   - { re: "^relayhost.*", line: "relayhost = [relay.example.com]:465" }
#   - { re: "^smtp_sasl_auth_enable.*", line: "smtp_sasl_auth_enable = yes" }
#   - { re: "^smtp_sasl_password_maps.*", line: "smtp_sasl_password_maps = hash:/etc/postfix/postfix_relay_pass" }
#   - { re: "^smtp_sasl_security_options.*", line: "smtp_sasl_security_options = noanonymous" }
#   - { re: "^smtp_tls_security_level.*", line: "smtp_tls_security_level = encrypt" }
#   - { re: "^smtp_tls_wrappermode.*", line: "smtp_tls_wrappermode = yes" }
#   - { re: "^smtp_use_tls.*", line: "smtp_use_tls = no" }

# isp_email_server_name: "mail.example.com"
# isp_email_server_port: "465"
# isp_email_address: "me@example.com"
# isp_email_tls: false
# isp_email_ssl: true
# isp_email_auth_username: "me@example.com"
# isp_email_auth_password: secret

# postfix relay authentication using /etc/postfix/postfix_relay_pass
# postfix_relay_pass: |
#   [{{ isp_email_server_name }}]:{{ isp_email_server_port }} {{ isp_email_auth_username }}:{{ isp_email_auth_password }}
