---
- name: "Manage roles"
  ipa_role:
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    host: "{{ item.host | default(omit) }}"
    hostgroup: "{{ item.hostgroup | default(omit) }}"
    privilege: "{{ item.privilege | default(omit) }}"
    service: "{{ item.service | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    user: "{{ item.user | default(omit) }}"
    # Connection settings
    ipa_host: "{{ ipa_manage_host }}"
    ipa_user: "{{ ipa_manage_user }}"
    ipa_pass: "{{ ipa_manage_pass }}"
    validate_certs: "{{ ipa_manage_validate_certs }}"
  with_items: "{{ ipa_manage_roles }}"
  loop_control:
    label: "{{ item.name }}"
  when: ipa_manage_roles | default([]) | length>0
