---
- name: "Manage users"
  ipa_user:
    name: "{{ item.name }}"
    displayname: "{{ item.displayname | default(omit) }}"
    givenname: "{{ item.givenname | default(omit) }}"
    homedirectory: "{{ item.homedirectory | default(omit) }}"
    krbpasswordexpiration: "{{ item.krbpasswordexpiration | default(omit) }}"
    loginshell: "{{ item.loginshell | default(omit) }}"
    mail: "{{ item.mail | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    sn: "{{ item.sn | default(omit) }}"
    sshpubkey: "{{ item.sshpubkey | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    update_password: "{{ item.update_password | default(omit) }}"
    # Connection settings
    ipa_host: "{{ ipa_manage_host }}"
    ipa_user: "{{ ipa_manage_user }}"
    ipa_pass: "{{ ipa_manage_pass }}"
    validate_certs: "{{ ipa_manage_validate_certs }}"
  register: _ipa_command_user
  with_items: "{{ ipa_manage_users }}"
  loop_control:
    label: "{{ item.name }}"
  failed_when: (_ipa_command_user.failed == true) and ("no modifications to be performed" not in _ipa_command_user.msg)
  when: ipa_manage_users | default([]) | length>0
