---

# Note: IDM do checks. If some unknown host is set here, it will not be added to the hostgroup despite the task succeed.

- name: "Manage hostgroups"
  ipa_hostgroup:
    name: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
    host: "{{ item.host | default(omit) }}"
    hostgroup: "{{ item.hostgroup | default(omit) }}"
    # Connection settings
    ipa_host: "{{ ipa_manage_host }}"
    ipa_user: "{{ ipa_manage_user }}"
    ipa_pass: "{{ ipa_manage_pass }}"
    validate_certs: "{{ ipa_manage_validate_certs }}"
  with_items: "{{ ipa_manage_hostgroups }}"
  loop_control:
    label: "{{ item.name }}"
  when: ipa_manage_hostgroups | default([]) | length>0
