---
- name: Include ipa_configs
  ansible.builtin.import_tasks: ipa_configs.yml
  when: ipa_configs is defined
  run_once: true

- name: Include ipa_users
  ansible.builtin.import_tasks: ipa_users.yml
  when: ipa_users is defined
  run_once: true

- name: Include ipa_groups
  ansible.builtin.import_tasks: ipa_groups.yml
  when: ipa_groups is defined
  run_once: true

- name: Include ipa_hostgroups
  ansible.builtin.import_tasks: ipa_hostgroups.yml
  when: ipa_hostgroups is defined
  run_once: true

- name: Include ipa_roles
  ansible.builtin.import_tasks: ipa_roles.yml
  when: ipa_roles is defined
  run_once: true

- name: Include ipa_hbacrules
  ansible.builtin.import_tasks: ipa_hbacrules.yml
  when: ipa_hbacrules is defined
  run_once: true

- name: Include ipa_sudorules
  ansible.builtin.import_tasks: ipa_sudorules.yml
  when: ipa_sudorules is defined
  run_once: true
